# Generated by Django 3.2.5 on 2021-07-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=25, verbose_name='Sobrenome')),
                ('nome_visualizacao', models.CharField(max_length=50, verbose_name='Nome de Visualização')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('imagem_perfil', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PESSOAS',
            },
        ),
    ]
