# Generated by Django 3.2.5 on 2021-07-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pessoa',
            table='pessoa',
        ),
    ]
