# Generated by Django 3.2.5 on 2021-07-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_pessoa_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoPretendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo Pretendido')),
            ],
        ),
        migrations.CreateModel(
            name='SobreMim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobremim', models.CharField(max_length=2000, verbose_name='Sobre Mim')),
            ],
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='imagem_perfil',
            field=models.CharField(max_length=200),
        ),
    ]
