# Generated by Django 3.2.5 on 2021-07-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_pessoa_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.CharField(max_length=300, verbose_name='LinkedIn')),
                ('github', models.CharField(max_length=300, verbose_name='GitHub')),
                ('whatsapp', models.CharField(max_length=14, verbose_name='Whatsapp')),
            ],
        ),
        migrations.CreateModel(
            name='SobreMim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobremim', models.CharField(max_length=2000, verbose_name='Sobre Mim')),
            ],
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='imagem_perfil',
            field=models.CharField(max_length=200),
        ),
    ]
